-- =====================================================
-- 分发侠 (ContentFlow) Phase 4 新功能数据库架构
-- 创建日期: 2026-01-10
-- =====================================================

-- 1. 增长目标设定表
CREATE TABLE IF NOT EXISTS growth_goals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    target_type VARCHAR(50) NOT NULL, -- 'followers', 'views', 'engagement', 'revenue'
    target_value BIGINT NOT NULL,
    period_type VARCHAR(20) NOT NULL DEFAULT 'monthly', -- 'weekly', 'monthly', 'quarterly', 'yearly'
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    current_value BIGINT DEFAULT 0,
    status VARCHAR(20) DEFAULT 'active', -- 'active', 'completed', 'failed'
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. 内容标注表（用于爆款拆解）
CREATE TABLE IF NOT EXISTS content_annotations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    content_id UUID, -- 关联 contents 表
    source_url TEXT,
    source_platform VARCHAR(50),
    annotation_type VARCHAR(50) NOT NULL, -- 'hook', 'structure', 'emotion', 'keyword', 'template'
    annotation_data JSONB NOT NULL,
    ai_analysis_result TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. 人设模板表
CREATE TABLE IF NOT EXISTS persona_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    is_system_template BOOLEAN DEFAULT FALSE,
    name VARCHAR(100) NOT NULL,
    category VARCHAR(50) NOT NULL, -- 'knowledge', 'lifestyle', 'entertainment', 'education', etc.
    description TEXT,
    tone_of_voice TEXT, -- 语气风格描述
    typical_topics TEXT[], -- 典型话题类型
    writing_examples TEXT[], -- 写作范例
    template_config JSONB, -- AI 生成时的配置参数
    usage_count INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. 账号健康度记录表
CREATE TABLE IF NOT EXISTS account_health (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    account_id UUID NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    check_date DATE NOT NULL,
    health_score INT DEFAULT 100, -- 0-100
    status VARCHAR(20) DEFAULT 'healthy', -- 'healthy', 'warning', 'limited', 'banned'
    issues JSONB, -- 检测到的问题列表
    recommendations JSONB, -- 改善建议
    metrics_snapshot JSONB, -- 当时的指标快照
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. 用户通知表（每日推送记录）
CREATE TABLE IF NOT EXISTS user_notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    notification_type VARCHAR(50) NOT NULL, -- 'daily_digest', 'hot_topic', 'content_alert', 'milestone'
    title VARCHAR(200) NOT NULL,
    content TEXT,
    metadata JSONB,
    is_read BOOLEAN DEFAULT FALSE,
    read_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. A/B 测试表
CREATE TABLE IF NOT EXISTS ab_tests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    content_id UUID REFERENCES contents(id) ON DELETE CASCADE,
    test_name VARCHAR(200) NOT NULL,
    variants JSONB NOT NULL, -- { "A": {content: "...", impressions: 0, clicks: 0}, "B": {...} }
    winner_variant VARCHAR(10),
    status VARCHAR(20) DEFAULT 'running', -- 'running', 'completed', 'paused'
    start_date TIMESTAMPTZ DEFAULT NOW(),
    end_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. 竞品监控表
CREATE TABLE IF NOT EXISTS competitor_monitors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    competitor_name VARCHAR(100) NOT NULL,
    competitor_platform VARCHAR(50) NOT NULL,
    account_url TEXT,
    last_checked_at TIMESTAMPTZ,
    last_post_date DATE,
    recent_posts JSONB, -- 最近发布的帖子数据
    engagement_stats JSONB, -- 互动统计数据
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, competitor_platform, account_url)
);

-- 8. 定时任务队列表（用于持久化）
CREATE TABLE IF NOT EXISTS scheduled_task_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_type VARCHAR(50) NOT NULL, -- 'publish', 'notification', 'health_check'
    task_payload JSONB NOT NULL,
    scheduled_at TIMESTAMPTZ NOT NULL,
    executed_at TIMESTAMPTZ,
    status VARCHAR(20) DEFAULT 'pending', -- 'pending', 'processing', 'completed', 'failed'
    retry_count INT DEFAULT 0,
    error_message TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. 内容预测评分表
CREATE TABLE IF NOT EXISTS content_predictions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_id UUID REFERENCES contents(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    platform VARCHAR(50) NOT NULL,
    predicted_score INT, -- 1-100 预估热度分数
    factors JSONB, -- 评分因素 { "title": 30, "timing": 20, "topic": 25, ... }
    confidence DECIMAL(5,2), -- 置信度 0-1
    actual_performance JSONB, -- 实际发布后的表现数据
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. 用户成长体系表
CREATE TABLE IF NOT EXISTS user_gamification (
    user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    level INT DEFAULT 1,
    experience_points INT DEFAULT 0,
    total_contents_created INT DEFAULT 0,
    total_published INT DEFAULT 0,
    streak_days INT DEFAULT 0, -- 连续发布天数
    last_active_date DATE,
    achievements JSONB DEFAULT '[]', -- 已获得的成就
    badges JSONB DEFAULT '[]',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- =====================================================
-- 索引优化
-- =====================================================

CREATE INDEX IF NOT EXISTS idx_growth_goals_user ON growth_goals(user_id);
CREATE INDEX IF NOT EXISTS idx_content_annotations_user ON content_annotations(user_id);
CREATE INDEX IF NOT EXISTS idx_persona_templates_user ON persona_templates(user_id);
CREATE INDEX IF NOT EXISTS idx_account_health_account ON account_health(account_id);
CREATE INDEX IF NOT EXISTS idx_user_notifications_user ON user_notifications(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_ab_tests_user ON ab_tests(user_id);
CREATE INDEX IF NOT EXISTS idx_competitor_monitors_user ON competitor_monitors(user_id);
CREATE INDEX IF NOT EXISTS idx_scheduled_task_queue_time ON scheduled_task_queue(scheduled_at, status);
CREATE INDEX IF NOT EXISTS idx_content_predictions_user ON content_predictions(user_id);

-- =====================================================
-- RLS 安全策略
-- =====================================================

ALTER TABLE growth_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE content_annotations ENABLE ROW LEVEL SECURITY;
ALTER TABLE persona_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE account_health ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE ab_tests ENABLE ROW LEVEL SECURITY;
ALTER TABLE competitor_monitors ENABLE ROW LEVEL SECURITY;
ALTER TABLE scheduled_task_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE content_predictions ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_gamification ENABLE ROW LEVEL SECURITY;

-- 用户只能看到自己的数据
CREATE POLICY "Users can view own growth goals" ON growth_goals FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can manage own growth goals" ON growth_goals FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Users can view own annotations" ON content_annotations FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can manage own annotations" ON content_annotations FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Users can view own personas" ON persona_templates FOR SELECT USING (auth.uid() = user_id OR is_system_template = TRUE);
CREATE POLICY "Users can manage own personas" ON persona_templates FOR ALL USING (auth.uid() = user_id OR is_system_template = FALSE);

CREATE POLICY "Users can view own account health" ON account_health FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can manage own account health" ON account_health FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Users can view own notifications" ON user_notifications FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can manage own notifications" ON user_notifications FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Users can view own AB tests" ON ab_tests FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can manage own AB tests" ON ab_tests FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Users can view own competitors" ON competitor_monitors FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can manage own competitors" ON competitor_monitors FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Users can view scheduled tasks" ON scheduled_task_queue FOR SELECT USING (auth.uid() = user_id OR task_payload->>'userId' = auth.uid()::text);
CREATE POLICY "System can manage scheduled tasks" ON scheduled_task_queue FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Users can view own predictions" ON content_predictions FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can manage own predictions" ON content_predictions FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Users can view own gamification" ON user_gamification FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can manage own gamification" ON user_gamification FOR ALL USING (auth.uid() = user_id);

-- =====================================================
-- 触发器
-- =====================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_growth_goals_updated_at BEFORE UPDATE ON growth_goals FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_persona_templates_updated_at BEFORE UPDATE ON persona_templates FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_ab_tests_updated_at BEFORE UPDATE ON ab_tests FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_competitor_monitors_updated_at BEFORE UPDATE ON competitor_monitors FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_user_gamification_updated_at BEFORE UPDATE ON user_gamification FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- =====================================================
-- 初始系统数据
-- =====================================================

-- 插入默认的人设模板
INSERT INTO persona_templates (is_system_template, name, category, description, tone_of_voice, typical_topics, writing_examples, template_config) VALUES
(TRUE, '知识博主', 'knowledge', '专业、严谨、善于深度分析的知识分享者', '专业且易懂', ARRAY['干货教程', '行业洞察', '技能提升', '读书笔记'], ARRAY['今天我们来聊聊...', '很多人不知道的是...', '背后的逻辑是...'], '{"style": "professional", "emojiFrequency": "low", "paragraphLength": "long"}'),
(TRUE, '种草达人', 'lifestyle', '擅长发现好物、分享生活的种草博主', '亲切热情', ARRAY['好物推荐', '护肤心得', '家居必备', '零食测评'], ARRAY['姐妹们！这个真的绝了！', '入手不亏系列！', '跪求你们一定要试试！'], '{"style": "xhs_influencer", "emojiFrequency": "high", "paragraphLength": "medium"}'),
(TRUE, '情感导师', 'entertainment', '洞察人心、治愈情感的情感博主', '温暖治愈', ARRAY['情感故事', '两性分析', '自我成长', '心理疗愈'], ARRAY['其实每个人...', '有时候我们...', '我想告诉你的是...'], '{"style": "humorous", "emojiFrequency": "medium", "paragraphLength": "medium"}'),
(TRUE, '科技极客', 'technology', '热爱科技、追求前沿的数码爱好者', '硬核专业', ARRAY['新品测评', '数码教程', 'AI工具', '编程技术'], ARRAY['技术角度来说...', '实测数据表明...', '底层逻辑是...'], '{"style": "professional", "emojiFrequency": "low", "paragraphLength": "long"}'),
(TRUE, '美食探店', 'lifestyle', '热爱美食、分享美味的美食博主', '活泼生动', ARRAY['餐厅测评', '食谱分享', '街头美食', '烘焙教程'], ARRAY['这家店真的绝了！', '答应我一定要去吃！', '在家也能做出店的味道！'], '{"style": "humorous", "emojiFrequency": "high", "paragraphLength": "medium"}'),
(TRUE, '职场导师', 'education', '职场经验分享、职业规划指导', '专业务实', ARRAY['职场干货', '面试技巧', '升职加薪', '领导力'], ARRAY['职场中...', '很多人误区在于...', '正确的做法是...'], '{"style": "professional", "emojiFrequency": "low", "paragraphLength": "medium"}');

-- 插入初始成就定义
INSERT INTO user_gamification (user_id, level, experience_points) VALUES
    -- 初始用户数据将由认证触发器自动创建
;

-- =====================================================
-- 数据库函数
-- =====================================================

-- 计算用户等级
CREATE OR REPLACE FUNCTION calculate_user_level(exp_points INT)
RETURNS INT AS $$
BEGIN
    RETURN FLOOR(SQRT(exp_points / 100)) + 1;
END;
$$ LANGUAGE plpgsql;

-- 添加经验值并更新等级
CREATE OR REPLACE FUNCTION add_experience_points(user_uuid UUID, points INT)
RETURNS VOID AS $$
BEGIN
    UPDATE user_gamification
    SET experience_points = experience_points + points,
        level = calculate_user_level(experience_points + points),
        updated_at = NOW()
    WHERE user_id = user_uuid;
END;
$$ LANGUAGE plpgsql;

-- 检查并更新连续活跃天数
CREATE OR REPLACE FUNCTION update_streak_days(user_uuid UUID)
RETURNS VOID AS $$
DECLARE
    last_active DATE;
    current_streak INT;
BEGIN
    SELECT last_active_date, streak_days INTO last_active, current_streak
    FROM user_gamification WHERE user_id = user_uuid;

    IF last_active IS NULL THEN
        UPDATE user_gamification SET streak_days = 1, last_active_date = CURRENT_DATE WHERE user_id = user_uuid;
    ELSIF last_active = CURRENT_DATE - 1 THEN
        UPDATE user_gamification SET streak_days = current_streak + 1, last_active_date = CURRENT_DATE WHERE user_id = user_uuid;
    ELSIF last_active < CURRENT_DATE - 1 THEN
        UPDATE user_gamification SET streak_days = 1, last_active_date = CURRENT_DATE WHERE user_id = user_uuid;
    END IF;
END;
$$ LANGUAGE plpgsql;

-- =====================================================
-- 完成
-- =====================================================

COMMENT ON TABLE growth_goals IS '用户增长目标设定';
COMMENT ON TABLE content_annotations IS '爆款内容拆解标注';
COMMENT ON TABLE persona_templates IS 'AI创作人设模板库';
COMMENT ON TABLE account_health IS '账号健康度监控记录';
COMMENT ON TABLE user_notifications IS '用户通知和每日推送';
COMMENT ON TABLE ab_tests IS '内容A/B测试记录';
COMMENT ON TABLE competitor_monitors IS '竞品账号监控';
COMMENT ON TABLE scheduled_task_queue IS '定时任务持久化队列';
COMMENT ON TABLE content_predictions IS 'AI预测评分记录';
COMMENT ON TABLE user_gamification IS '用户成长体系和成就';
